excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://thomallen.github.io
title: Thom Allen
tagline: <coder />
description: #Mormon, #Marine, #MobileFirst, #Coder, #WordPress, #Technology, #CTO, #CIO, #NASCAR, Fighting #Cancer, #ManchesterUnited, http://fb.com/thomallen
paginate: 5
